name: Stock Prediction Workflow org

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ticker: ['RELIANCE.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'ITC.NS', 'ETERNAL.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'DLF.NS', 'SBILIFE.NS', 'VBL.NS', 'PFC.NS', 'RECLTD.NS', 'ADANIENSOL.NS', 'INDIANB.NS', 'SUZLON.NS', 'ABCAPITAL.NS', 'PRESTIGE.NS', 'GVT&D.NS', 'LLOYDSME.NS', 'FORTIS.NS', 'PATANJALI.NS', 'MFSL.NS', 'MOTILALOFS.NS', 'KALYANKJIL.NS', 'ITCHOTELS.NS', 'HEXT.NS', '360ONE.NS', 'HUDCO.NS', 'COHANCE.NS', 'ASTERDM.NS', 'KIMS.NS', 'PPLPHARMA.NS', 'BRIGADE.NS', 'WELCORP.NS', 'CHALET.NS', 'AADHARHFC.NS', 'ONESOURCE.NS', 'SAGILITY.NS', 'KARURVYSYA.NS', 'PNBHOUSING.NS', 'CROMPTON.NS', 'ABREL.NS', 'BIKAJI.NS', 'SAILIFE.NS', 'ANANTRAJ.NS', 'CGCL.NS', 'TECHNOE.NS', 'VENTIVE.NS', 'RATNAMANI.NS', 'TRITURBINE.NS', 'AFCONS.NS', 'SIGNATURE.NS', 'ATHERENERG.NS', 'RAINBOW.NS', 'TBOTEK.NS', 'TARIL.NS', 'DOMS.NS', 'ABDL.NS', 'KIRLOSENG.NS', 'THELEELA.NS', 'RRKABEL.NS', 'LEMONTREE.NS', 'JINDALSAW.NS', 'GRAVITA.NS', 'BALRAMCHIN.NS', 'ALIVUS.NS', 'CELLO.NS', 'TITAGARH.NS', 'GRANULES.NS', 'AZAD.NS', 'MEDPLUS.NS', 'INDIASHLTR.NS', 'AETHER.NS', 'BIRLACORPN.NS', 'ASTRAMICRO.NS', 'WABAG.NS', 'JLHL.NS', 'TCI.NS', 'BECTORFOOD.NS', 'RUSTOMJEE.NS', 'KIRLPNU.NS', 'DODLA.NS', 'ARVIND.NS', 'EPL.NS', 'AKUMS.NS', 'MAXESTATES.NS', 'ARVINDFASN.NS', 'CHEMPLASTS.NS', 'THANGAMAYL.NS', 'MOIL.NS', 'CSBBANK.NS', 'JUNIPER.NS', 'KTKBANK.NS', 'AVL.NS', 'GULFOILLUB.NS', 'SUNTECK.NS', 'BANSALWIRE.NS', 'MASFIN.NS', 'SIS.NS', 'FEDFINA.NS', 'BALAMINES.NS', 'EMIL.NS', 'VRLLOG.NS', 'JKIL.NS', 'SAMHI.NS', 'AWFIS.NS', 'WONDERLA.NS', 'QUESS.NS', 'ORCHPHARMA.NS', 'KOLTEPATIL.NS', 'MEDIASSIST.NS', 'DCBBANK.NS', 'NEOGEN.NS', 'GOCOLORS.NS', 'EPACK.NS', 'ROSSARI.NS', 'GATEWAY.NS', 'FLAIR.NS', 'BAJAJCON.NS', 'JTLIND.NS', 'ARVSMART.NS', 'LAOPALA.NS', 'MOLDTKPAC.NS', 'VENUSPIPES.NS', 'KRSNAA.NS', 'YATRA.NS', 'STOVEKRAFT.NS', 'LAXMIDENTL.NS', 'UDS.NS']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas scikit-learn tensorflow matplotlib scipy

    - name: Run stock prediction
      id: predict
      run: |
        # Run the script and capture the output
        python ssorg.py ${{ matrix.ticker }} > output.log

        # Extract values using more precise grep patterns
        acc=$(grep "Directional Accuracy:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        rmse=$(grep "RMSE:" output.log | awk -F': ' '{print $2}')
        mae=$(grep "MAE:" output.log | awk -F': ' '{print $2}')
        change=$(grep "PERCENT CHANGE:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        direction=$(grep "DIRECTION:" output.log | awk -F': ' '{print $2}')

        # Append formatted summary to GitHub step summary
        echo "### ðŸ“Š ${{ matrix.ticker }}" >> $GITHUB_STEP_SUMMARY
        echo "ðŸŽ¯ Accuracy: ${acc}% | ðŸ“ˆ RMSE: ${rmse} | ðŸ“‰ MAE: ${mae} | Î”%: ${change}% | ðŸ§­ Dir: ${direction}" >> $GITHUB_STEP_SUMMARY
