name: Stock Prediction Workflow org

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ticker: ['RELIANCE.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'ITC.NS', 'SUNPHARMA.NS', 'NTPC.NS', 'ETERNAL.NS', 'ADANIPORTS.NS', 'ADANIENT.NS', 'ADANIPOWER.NS', 'HYUNDAI.NS', 'DLF.NS', 'SBILIFE.NS', 'VBL.NS', 'HDFCLIFE.NS', 'ADANIGREEN.NS', 'PFC.NS', 'LODHA.NS', 'SHRIRAMFIN.NS', 'RECLTD.NS', 'ADANIENSOL.NS', 'INDIANB.NS', 'SUZLON.NS', 'ABCAPITAL.NS', 'GVT&D.NS', 'LLOYDSME.NS', 'FORTIS.NS', 'PRESTIGE.NS', 'PATANJALI.NS', 'AUROPHARMA.NS', 'MFSL.NS', 'MOTILALOFS.NS', 'KALYANKJIL.NS', 'ITCHOTELS.NS', 'HEXT.NS', 'GODREJIND.NS', '360ONE.NS', 'HUDCO.NS', 'MAHABANK.NS', 'COHANCE.NS', 'NLCINDIA.NS', 'ASTERDM.NS', 'SUMICHEM.NS', 'KIMS.NS', 'MSUMI.NS', 'PPLPHARMA.NS', 'EIHOTEL.NS', 'INOXWIND.NS', 'BRIGADE.NS', 'WELCORP.NS', 'HSCL.NS', 'AADHARHFC.NS', 'CHALET.NS', 'KPIL.NS', 'CESC.NS', 'JYOTICNC.NS', 'SAGILITY.NS', 'ONESOURCE.NS', 'SUNDRMFAST.NS', 'EIDPARRY.NS', 'PNBHOUSING.NS', 'KARURVYSYA.NS', 'SCHNEIDER.NS', 'CROMPTON.NS', 'ABREL.NS', 'SAILIFE.NS', 'DEEPAKFERT.NS', 'BIKAJI.NS', 'ANANTRAJ.NS', 'CGCL.NS', 'TECHNOE.NS', 'ACMESOLAR.NS', 'VENTIVE.NS', 'APTUS.NS', 'TRITURBINE.NS', 'RATNAMANI.NS', 'CAPLIPOINT.NS', 'RAINBOW.NS', 'AFCONS.NS', 'SIGNATURE.NS', 'CUB.NS', 'TBOTEK.NS', 'ATHERENERG.NS', 'LTFOODS.NS', 'DOMS.NS', 'TARIL.NS', 'SPLPETRO.NS', 'ABDL.NS', 'TRIDENT.NS', 'DATAPATTNS.NS', 'KSB.NS', 'THELEELA.NS', 'GESHIP.NS', 'KIRLOSENG.NS', 'RRKABEL.NS', 'LEMONTREE.NS', 'NETWEB.NS', 'BELRISE.NS', 'FINCABLES.NS', 'JINDALSAW.NS', 'GRAVITA.NS', 'ELECON.NS', 'SBFC.NS', 'CELLO.NS', 'ALIVUS.NS', 'BALRAMCHIN.NS', 'ACUTAAS.NS', 'TITAGARH.NS', 'SHRIPISTON.NS', 'USHAMART.NS', 'J&KBANK.NS', 'SUDARSCHEM.NS', 'GRANULES.NS', 'GENUSPOWER.NS', 'TIMETECHNO.NS', 'VESUVIUS.NS', 'ENGINERSIN.NS', 'EUREKAFORB.NS', 'GRAPHITE.NS', 'TRANSRAILL.NS', 'INOXINDIA.NS', 'AZAD.NS', 'AETHER.NS', 'NESCO.NS', 'ASKAUTOLTD.NS', 'BIRLACORPN.NS', 'WABAG.NS', 'MEDPLUS.NS', 'INDIASHLTR.NS', 'ASTRAMICRO.NS', 'TI.NS', 'MAPMYINDIA.NS', 'HEG.NS', 'JAIBALAJI.NS', 'JLHL.NS', 'MAHSEAMLES.NS', 'HAPPYFORGE.NS', 'TCI.NS', 'AVANTIFEED.NS', 'GMRP&UI.NS', 'UJJIVANSFB.NS', 'BECTORFOOD.NS', 'KIRLPNU.NS', 'TANLA.NS', 'RUSTOMJEE.NS', 'MARKSANS.NS', 'DODLA.NS', 'BBOX.NS', 'THOMASCOOK.NS', 'GARFIBRES.NS', 'STAR.NS', 'EPIGRAL.NS', 'PNGJL.NS', 'LUMAXTECH.NS', 'ARVIND.NS', 'EPL.NS', 'AKUMS.NS', 'AURIONPRO.NS', 'MAXESTATES.NS', 'MIDHANI.NS', 'MHRIL.NS', 'RAYMONDLSL.NS', 'CSBBANK.NS', 'ARVINDFASN.NS', 'CHEMPLASTS.NS', 'PURVA.NS', 'ETHOSLTD.NS', 'THYROCARE.NS']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas scikit-learn tensorflow matplotlib scipy

    - name: Run stock prediction
      id: predict
      run: |
        # Run the script and capture the output
        python ssorg.py ${{ matrix.ticker }} > output.log

        # Extract values using more precise grep patterns
        acc=$(grep "Directional Accuracy:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        rmse=$(grep "RMSE:" output.log | awk -F': ' '{print $2}')
        mae=$(grep "MAE:" output.log | awk -F': ' '{print $2}')
        change=$(grep "PERCENT CHANGE:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        direction=$(grep "DIRECTION:" output.log | awk -F': ' '{print $2}')

        # Append formatted summary to GitHub step summary
        echo "### ðŸ“Š ${{ matrix.ticker }}" >> $GITHUB_STEP_SUMMARY
        echo "ðŸŽ¯ Accuracy: ${acc}% | ðŸ“ˆ RMSE: ${rmse} | ðŸ“‰ MAE: ${mae} | Î”%: ${change}% | ðŸ§­ Dir: ${direction}" >> $GITHUB_STEP_SUMMARY
