name: Stock Prediction Workflow org

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ticker: [ "TCS.NS", "INFY.NS", "RELIANCE.NS", "HDFCBANK.NS", "SBIN.NS", "ICICIBANK.NS", "AXISBANK.NS", "KOTAKBANK.NS", "WIPRO.NS", "HCLTECH.NS", "ITC.NS", "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS","MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS"] # 👈 add 18 tickers here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas scikit-learn tensorflow matplotlib scipy

    - name: Run stock prediction
      run: python ssorg.py ${{ matrix.ticker }}
