name: Stock Prediction Workflow org

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ticker: [ 'RELIANCE.NS','HDFCBANK.NS', 'ICICIBANK.NS' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas scikit-learn tensorflow matplotlib scipy

    - name: Run stock prediction
      id: predict
      run: |
        # Run the script and capture the output
        python ssorg.py ${{ matrix.ticker }} > output.log

        # Extract values using more precise grep patterns
        acc=$(grep "Directional Accuracy:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        rmse=$(grep "RMSE:" output.log | awk -F': ' '{print $2}')
        mae=$(grep "MAE:" output.log | awk -F': ' '{print $2}')
        change=$(grep "PERCENT CHANGE:" output.log | awk -F': ' '{print $2}' | tr -d '%')
        direction=$(grep "DIRECTION:" output.log | awk -F': ' '{print $2}')

        # Append formatted summary to GitHub step summary
        echo "### ðŸ“Š ${{ matrix.ticker }}" >> $GITHUB_STEP_SUMMARY
        echo "ðŸŽ¯ Accuracy: ${acc}% | ðŸ“ˆ RMSE: ${rmse} | ðŸ“‰ MAE: ${mae} | Î”%: ${change}% | ðŸ§­ Dir: ${direction}" >> $GITHUB_STEP_SUMMARY
